// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLittleRPG_Etape3.Data.Context;

#nullable disable

namespace MyLittleRPG_Etape3.Migrations
{
    [DbContext(typeof(RPGContext))]
    [Migration("20260916003428_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyLittleRPG_Etape3.Models.Monster", b =>
                {
                    b.Property<int>("idMonster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DefenseBase")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceBase")
                        .HasColumnType("int");

                    b.Property<int>("ForceBase")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PointsVieBase")
                        .HasColumnType("int");

                    b.Property<string>("SpriteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type2")
                        .HasColumnType("longtext");

                    b.HasKey("idMonster");

                    b.ToTable("Monster");
                });
#pragma warning restore 612, 618
        }
    }
}
