// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLittleRPG_Etape3.Data.Context;

#nullable disable

namespace MyLittleRPG_Etape3.Migrations
{
    [DbContext(typeof(RPGContext))]
    partial class MonsterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyLittleRPG_Etape3.Models.Monster", b =>
                {
                    b.Property<int>("idMonster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DefenseBase")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceBase")
                        .HasColumnType("int");

                    b.Property<int>("ForceBase")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PointsVieBase")
                        .HasColumnType("int");

                    b.Property<string>("SpriteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type2")
                        .HasColumnType("longtext");

                    b.HasKey("idMonster");

                    b.ToTable("Monster");
                });

            modelBuilder.Entity("MyLittleRPG_Etape3.Models.Tile", b =>
                {
                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<bool>("CanPass")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SpriteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("X", "Y");

                    b.ToTable("Tile");
                });
#pragma warning restore 612, 618
        }
    }
}
